"""
Supabase 테이블 직접 생성 스크립트
PostgreSQL 연결을 통해 직접 테이블을 생성합니다.
"""

import sys
import psycopg2
from urllib.parse import urlparse

# Windows 콘솔 인코딩 설정
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Supabase 연결 정보
SUPABASE_URL = "https://sbwwmartlnxadktagwvx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNid3dtYXJ0bG54YWRrdGFnd3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NjM1MTgsImV4cCI6MjA4MzMzOTUxOH0.8EC0zI5p-xzTa0LKL2n7ICbUC2exvJaRYa5IkR4usEs"

# SQL 쿼리
CREATE_TABLES_SQL = """
-- 1. 보험 상품 테이블
CREATE TABLE IF NOT EXISTS insurance_products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    product_name text not null,
    company text,
    analysis_data jsonb,
    user_id text
);

-- 2. 상담 이력 테이블
CREATE TABLE IF NOT EXISTS consulting_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    customer_name text,
    agent_name text,
    recommended_product_id bigint references insurance_products(id),
    analysis_result jsonb,
    user_id text
);

-- 인덱스 생성 (성능 향상)
CREATE INDEX IF NOT EXISTS idx_insurance_products_created_at ON insurance_products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_created_at ON consulting_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_customer_name ON consulting_history(customer_name);
"""

def create_tables():
    """Supabase에 직접 테이블 생성"""
    print("Supabase 테이블 생성 스크립트 시작\n")
    
    # Supabase는 직접 PostgreSQL 연결을 지원하지 않으므로
    # Supabase 대시보드에서 SQL을 실행해야 합니다
    print("Supabase Python 클라이언트는 직접 SQL 실행을 지원하지 않습니다.")
    print("Supabase 대시보드에서 SQL Editor를 열고 다음 SQL을 실행하세요:\n")
    print("=" * 60)
    print(CREATE_TABLES_SQL)
    print("=" * 60)
    print("\n또는 다음 URL로 직접 이동하세요:")
    print(f"https://supabase.com/dashboard/project/sbwwmartlnxadktagwvx/sql/new")
    
    return False

if __name__ == "__main__":
    create_tables()

