"""
Supabase 테이블 생성 스크립트
이 스크립트를 실행하면 Supabase에 필요한 테이블이 자동으로 생성됩니다.
"""

import os
import sys
from supabase import create_client

# Windows 콘솔 인코딩 설정
if sys.platform == 'win32':
    sys.stdout.reconfigure(encoding='utf-8')

# Supabase 연결 정보
SUPABASE_URL = "https://sbwwmartlnxadktagwvx.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNid3dtYXJ0bG54YWRrdGFnd3Z4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njc3NjM1MTgsImV4cCI6MjA4MzMzOTUxOH0.8EC0zI5p-xzTa0LKL2n7ICbUC2exvJaRYa5IkR4usEs"

# SQL 쿼리
CREATE_TABLES_SQL = """
-- 1. 보험 상품 테이블
CREATE TABLE IF NOT EXISTS insurance_products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    product_name text not null,
    company text,
    analysis_data jsonb,
    user_id text
);

-- 2. 상담 이력 테이블
CREATE TABLE IF NOT EXISTS consulting_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    customer_name text,
    agent_name text,
    recommended_product_id bigint references insurance_products(id),
    analysis_result jsonb,
    user_id text
);

-- 인덱스 생성 (성능 향상)
CREATE INDEX IF NOT EXISTS idx_insurance_products_created_at ON insurance_products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_created_at ON consulting_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_customer_name ON consulting_history(customer_name);
"""

def create_tables():
    """Supabase에 테이블 생성"""
    try:
        # Supabase 클라이언트 생성
        supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
        
        print("✅ Supabase 연결 성공!")
        print("📋 테이블 생성 중...")
        
        # Supabase는 RPC를 통해 SQL 실행
        # 하지만 직접 SQL 실행은 관리자 권한이 필요하므로
        # Supabase 관리 API를 사용하거나 psycopg2를 사용해야 합니다
        
        # 대신 테이블이 존재하는지 확인하고 안내
        try:
            # 테이블 존재 확인
            result = supabase.table("insurance_products").select("id").limit(1).execute()
            print("✅ insurance_products 테이블이 이미 존재합니다.")
        except Exception:
            print("⚠️ insurance_products 테이블이 없습니다.")
            print("\n💡 Supabase 대시보드에서 SQL Editor를 열고 다음 SQL을 실행하세요:\n")
            print(CREATE_TABLES_SQL)
            return False
        
        try:
            result = supabase.table("consulting_history").select("id").limit(1).execute()
            print("✅ consulting_history 테이블이 이미 존재합니다.")
        except Exception:
            print("⚠️ consulting_history 테이블이 없습니다.")
            print("\n💡 Supabase 대시보드에서 SQL Editor를 열고 다음 SQL을 실행하세요:\n")
            print(CREATE_TABLES_SQL)
            return False
        
        print("\n✅ 모든 테이블이 준비되었습니다!")
        return True
        
    except Exception as e:
        print(f"❌ 오류 발생: {str(e)}")
        print("\n💡 Supabase 대시보드에서 SQL Editor를 열고 다음 SQL을 실행하세요:\n")
        print(CREATE_TABLES_SQL)
        return False

if __name__ == "__main__":
    print("🚀 Supabase 테이블 생성 스크립트 시작\n")
    create_tables()

