-- Supabase 데이터베이스 테이블 생성 SQL
-- 이 파일의 내용을 Supabase SQL Editor에서 실행하세요.

-- 1. 보험 상품 테이블
CREATE TABLE IF NOT EXISTS insurance_products (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    product_name text not null,
    company text,
    analysis_data jsonb, -- AI 분석 결과 (보장내역)
    user_id text -- 등록한 관리자 ID (현재는 "admin-temp-id" 사용)
);

-- 2. 상담 이력 테이블
CREATE TABLE IF NOT EXISTS consulting_history (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    customer_name text,
    agent_name text,
    recommended_product_id bigint references insurance_products(id),
    analysis_result jsonb, -- AI 비교 분석 결과
    user_id text -- 상담한 설계사 ID (현재는 "agent-temp-id" 사용)
);

-- 인덱스 생성 (성능 향상)
CREATE INDEX IF NOT EXISTS idx_insurance_products_created_at ON insurance_products(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_created_at ON consulting_history(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_consulting_history_customer_name ON consulting_history(customer_name);

